eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            inventory:
                automaticTransitionFromOpenToHalfOpenEnabled: true
                event-consumer-buffer-size: 10
                failureRateThreshold: 50
                permittedNumberOfCallsInHalfOpenState: 3
                registerHealthIndicator: true
                slidingWindowSize: 5
                slidingWindowType: COUNT_BASED
                waitDurationInOpenState: 5s
    retry:
        instances:
            inventory:
                max-attempts: 3
                wait-duration: 5s
    timelimiter:
        instances:
            inventory:
                timeout-duration: 3s
server:
    port: 0
spring:
    application:
        name: order-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/order-service
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
